import Head from 'next/head'
export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome Ally</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome Ally</h1>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe tempore possimus nemo accusamus dolore culpa.</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe tempore possimus nemo accusamus dolore culpa.</p>
      </main>
    </>
  )
}
