import Head from "next/head";
import Image from "next/image";
import CommentForm from "../comps/CommentForm";
import Comments from "../comps/Comments";
export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome Ally</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section style={{ minWidth: "320px" }} className="float-lg-end ms-lg-5 text-center">
          <hr />
          <img
            className="d-block mx-auto"
            style={{ width: "200px" }}
            alt="Spotify"
            src="https://upload.wikimedia.org/wikipedia/commons/2/26/Spotify_logo_with_text.svg"
          />
          <hr />
          <table className="table">
            <tbody>
              <tr>
                <th scope="row">Structure & Layout</th>
                <td className="fs-3">
                  5
                  <div className="d-inline-block ms-3">
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                  </div>
                </td>
              </tr>
              <tr>
                <th scope="row">Responsiveness</th>
                <td className="fs-3">
                  5
                  <div className="d-inline-block ms-3">
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                  </div>
                </td>
              </tr>
              <tr>
                <th scope="row">Forms & Controls</th>
                <td className="fs-3">
                  5
                  <div className="d-inline-block ms-3">
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                  </div>
                </td>
              </tr>
              <tr>
                <th scope="row">Labels</th>
                <td className="fs-3">
                  4
                  <div className="d-inline-block ms-3">
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                  </div>
                </td>
              </tr>
              <tr>
                <th scope="row">Image Descriptions</th>
                <td className="fs-3">
                  5
                  <div className="d-inline-block ms-3">
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                  </div>
                </td>
              </tr>
              <tr>
                <th scope="row">Legibility</th>
                <td className="fs-3">
                  5
                  <div className="d-inline-block ms-3">
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                  </div>
                </td>
              </tr>
              <tr>
                <th scope="row">Colours & Contrast</th>
                <td className="fs-3">
                  4
                  <div className="d-inline-block ms-3">
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                  </div>
                </td>
              </tr>
              <tr>
                <th scope="row">Useful Features</th>
                <td className="fs-3">
                  5
                  <div className="d-inline-block ms-3">
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                  </div>
                </td>
              </tr>
              <tr>
                <th scope="row">User Rating</th>
                <td className="fs-3">
                  4
                  <div className="d-inline-block ms-3">
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                    <img src="/star-fill.svg" />
                  </div>
                </td>
              </tr>
              <tr>
                <th scope="row">Final Score</th>
                <td className="fs-3">4.75</td>
              </tr>
            </tbody>
          </table>
        </section>
        <section className="mb-5">
          <h1 className="mb-4">Spotify</h1>
          <div className="d-block d-md-none float-start me-3 mb-1">
            <Image
              src="/gold.png"
              alt="Welcome Ally Gold Award"
              width={150}
              height={150}
            />
          </div>
          <div className="d-none d-md-block float-start me-3 mb-1">
            <Image
              src="/gold.png"
              alt="Welcome Ally Gold Award"
              width={250}
              height={250}
            />
          </div>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit
            architecto tempore repudiandae, illum blanditiis ea ducimus delectus
            aliquam aliquid impedit nulla eveniet quasi nisi quisquam
            perferendis? Dicta beatae saepe eveniet laborum, illo rerum
            perspiciatis vel sapiente architecto a tenetur quisquam placeat
            mollitia veniam inventore debitis ducimus quis, est officia
            repellat?
          </p>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit
            architecto tempore repudiandae, illum blanditiis ea ducimus delectus
            aliquam aliquid impedit nulla eveniet quasi nisi quisquam
            perferendis? Dicta beatae saepe eveniet laborum, illo rerum
            perspiciatis vel sapiente architecto a tenetur quisquam placeat
            mollitia veniam inventore debitis ducimus quis, est officia
            repellat?
          </p>
          <p className="text-success">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit
            architecto tempore repudiandae, illum blanditiis ea ducimus delectus
            aliquam aliquid impedit nulla eveniet quasi nisi quisquam
            perferendis? Dicta beatae saepe eveniet laborum, illo rerum
            perspiciatis vel sapiente architecto a tenetur quisquam placeat
            mollitia veniam inventore debitis ducimus quis, est officia
            repellat?
          </p>
        </section>
        <CommentForm />
        <Comments />
      </main>
    </>
  );
}